// One Small Thing — the prompt bank.
// Everyone on Earth sees the same prompt on the same UTC day (see hashDate
// in app.js). Add more any time; nothing needs to be removed, ordered, or
// dated — the selection just cycles through whatever's here.
//
// Written deliberately specific and concrete, not vague positivity
// ("be kind today"). A prompt should be something you could actually
// picture yourself doing in the next hour.

const PROMPTS = [
  "Send a voice note to a friend telling them a specific memory you have of them — not just \"thinking of you.\"",
  "Text the last person who helped you through something hard and tell them, specifically, what it meant.",
  "Leave a genuine, specific review for a small local place you actually like.",
  "Message a coworker to say something they did well recently — name the actual thing.",
  "Write down the one thing you've been avoiding, then take the smallest possible step on it. Just the smallest one.",
  "Ask someone a real question about their life today and let them finish their answer without planning what you'll say next.",
  "Say something genuinely kind to someone providing you a service today — a barista, a driver, a cashier.",
  "Forgive yourself, out loud, for one specific thing you've been quietly carrying.",
  "Call — actually call, don't text — someone you've been meaning to check in on.",
  "Tell someone exactly what you appreciate about them, in detail, before the day ends.",
  "Fix one small thing you've been stepping over or ignoring at home.",
  "Give up your seat, your place in line, or five minutes of your time to someone who needs it more today.",
  "Write a two-line note to your future self about what's actually going well right now.",
  "Apologize for something small and specific that you've been quietly justifying instead of just saying sorry for.",
  "Ask an older relative one question about their life you've never asked before.",
  "Pick up a piece of litter you pass today, if you can do it safely.",
  "Tell a friend one thing you're proud of them for — something real, not a compliment on autopilot.",
  "Sit outside for ten minutes without your phone. Just look at something.",
  "Reach out to someone you had a falling-out with and open the door, even a crack.",
  "Pay for the person behind you, if you're somewhere that makes that possible today.",
  "Write down three things that are true and good about your life right now, even if today is hard.",
  "Tell someone you were wrong about something, clearly, without adding a \"but.\"",
  "Give a genuine compliment to a stranger today — specific, not generic.",
  "Ask someone how they're really doing, and stay for the real answer.",
  "Do the dish, the email, or the errand you've been putting off for exactly this reason: it's small.",
  "Tell your parents, or whoever raised you, one specific thing you're grateful they taught you.",
  "Donate the cost of your next coffee to something that matters to you, if you're able.",
  "Write a short, specific thank-you to a teacher, mentor, or boss who actually helped you once.",
  "Let go of one grudge today, at least for the day. Just notice what that feels like.",
  "Ask a question in a meeting or conversation you'd normally stay quiet in.",
  "Compliment someone's work directly to their face, not behind their back where it doesn't reach them.",
  "Spend fifteen minutes actually learning something you've been curious about, for no other reason than curiosity.",
  "Tell someone what you're afraid of. Just one person. Just one fear.",
  "Give a genuine second chance to someone you've quietly written off.",
  "Write down one belief you hold and ask yourself honestly what would change your mind.",
  "Say no to something today that you'd normally say yes to out of guilt.",
  "Check in on someone who went quiet recently. People often go quiet right when they need someone to notice.",
  "Tell a sibling or old friend something you never got around to saying.",
  "Make eye contact and actually greet someone you usually just nod at.",
  "Write down the last time someone helped you, and thank them for it — even if it was years ago.",
  "Do one thing today entirely for its own sake, with no goal attached to it.",
  "Ask someone what they need help with this week, and actually help with it.",
  "Tell someone a joke that's actually for them, not for the room.",
  "Spend today's scrolling time on one phone call instead. Just today.",
  "Compliment a stranger's kid, dog, or effort — the small, easy-to-skip kind of praise.",
  "Write down what you'd tell your younger self about the thing you're worried about right now.",
  "Give someone the benefit of the doubt today, on purpose, even when it's hard.",
  "Ask a question you're embarrassed you don't already know the answer to.",
  "Text someone \"no reason, just thinking of you\" and mean it.",
  "Notice one thing that's beautiful today and tell someone about it.",
  "Let someone finish a story you've heard before, without saying \"I know.\"",
  "Do a chore that isn't yours, without announcing it.",
  "Write a specific, honest compliment for someone and actually send it instead of just thinking it.",
  "Ask a stranger for a recommendation — a book, a place, a song — and actually try it.",
  "Tell someone what they mean to you before an occasion makes you say it anyway.",
  "Sit with a hard feeling for five minutes today instead of numbing it with your phone.",
  "Reply to the message you've been meaning to reply to for a week.",
  "Give someone credit publicly for something they usually do quietly.",
  "Ask a coworker or classmate one thing about their weekend and actually listen.",
  "Write down one thing you did well this month that you haven't given yourself credit for.",
  "Offer to carry, hold, or help with something for a stranger today.",
  "Tell a friend the truth about something, kindly, instead of the easy comfortable lie.",
  "Let someone else be right today, even when you're pretty sure you're not wrong.",
  "Spend ten minutes tidying one small space, just for the version of you who'll walk into it later.",
  "Ask someone what kind of support actually helps them, instead of guessing.",
  "Write a short list of people who've shaped who you are, and thank one of them.",
  "Do something today that your future self will be glad you did, even if present-you doesn't feel like it.",
  "Notice someone who looks like they're having a hard day and offer one small kindness.",
  "Ask a friend a follow-up question about something they mentioned weeks ago — show them you remembered.",
  "Write down what you're avoiding thinking about, then think about it for five honest minutes.",
  "Tell someone specifically how they've grown, if you've known them a while.",
  "Give away something you don't need to someone who does.",
  "Say thank you to someone for something they probably think went unnoticed.",
  "Ask someone what they're proud of lately — most people never get asked.",
  "Take one photo today not to post, but just to remember.",
  "Write a short note of encouragement to someone who's mid-way through something hard.",
  "Tell someone exactly why you trust them.",
  "Do the uncomfortable, honest version of a conversation you've been avoiding the easy way around.",
  "Notice one assumption you're making about someone today, and check if it's actually true.",
  "Spend today's commute or downtime with your own thoughts instead of a feed.",
  "Ask someone what they need less advice and more just support with.",
  "Tell a friend one thing you admire about how they handle something hard.",
  "Write down the smallest version of a big goal, and do that smallest version today.",
  "Compliment someone on something they worked hard at, even if the result wasn't perfect.",
  "Reach out first, for once, instead of waiting for someone else to.",
  "Give a real answer the next time someone asks how you're doing.",
  "Tell someone what you learned from a mistake they don't know you made.",
  "Ask an expert or someone experienced one genuine question instead of pretending to already know.",
  "Notice something you take for granted today, and say thank you for it out loud.",
  "Write a short, honest message to someone you've lost touch with, no explanation needed for why.",
  "Do one kind thing today with absolutely no way for anyone to find out it was you.",
];
