export const CATEGORIES = [
  "Bread-and-Butter Analog",
  "Leads & Solo Instruments",
  "Motion & Modulated",
  "Percussive & Plucked",
  "Drones & Atmospheric",
  "Aggressive / Experimental",
  "Bell-Like / Metallic",
  "Keyboard-Tracking Variants",
  "Utility / Foundational",
];
export const PRESETS = [
  {
    name: "Classic Analog Bass",
    category: "Bread-and-Butter Analog",
    blurb:
      "The workhorse Moog/Prophet-style bass: a raw, fast-moving low end built from a single oscillator's harmonics reinforced by a sub, then snapped into shape by a quick filter envelope so the attack has punch without staying bright.",
    osc: "Osc 1 shape: saw or square; Osc 2 an octave down as sub reinforcement",
    mixer: "Osc 1 and Sub high, Osc 2/Noise low or off",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "min", octave: "low", pitch: "mid", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "high",
      fm: false,
      osc2: "low",
      noise: "min",
    },
    filterText:
      "Cutoff low-to-mid, moderate resonance, Env Amount high for a fast sweep",
    filterEnvText:
      "Fast Attack, short-to-medium Decay, low Sustain, short Release",
    ampEnvText:
      "Fast Attack, Sustain high enough to hold the note, short Release",
    filter: { cutoff: "low", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "low", sustain: "low", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Warm Pad",
    category: "Bread-and-Butter Analog",
    blurb:
      "A lush, slowly-blooming pad: two detuned saws for width and movement, a slow filter envelope that opens gradually, and gentle LFO drift so it never feels static.",
    osc: "Osc 1 + Osc 2 both saw, Osc 2 slightly detuned (Pitch a few cents off)",
    mixer: "Osc 1 and Osc 2 balanced, Sub/Noise off",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "mid", pitch: "low", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText: "Cutoff starts low, moderate resonance, Env Amount moderate",
    filterEnvText: "Slow Attack, long Decay, high Sustain, long Release",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "low", resonance: "low", drive: "low" },
    filterEnv: {
      attack: "high",
      decay: "high",
      sustain: "high",
      release: "high",
    },
    ampEnv: { attack: "high", decay: "mid", sustain: "high", release: "high" },
  },
  {
    name: "Soft Triangle Pad",
    category: "Bread-and-Butter Analog",
    blurb:
      "A gentler, rounder pad than the saw version - triangle waves are already low in harmonics, so a low cutoff and slow attack give a soft, breathy swell rather than a bright wash.",
    osc: "Osc 1 + Osc 2 both triangle wave",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "min", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "min", octave: "mid", pitch: "mid", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText:
      "Cutoff low, low resonance, Env Amount low (triangle needs little filtering)",
    filterEnvText: "Slow Attack, long Decay, high Sustain, long Release",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "low", resonance: "min", drive: "min" },
    filterEnv: {
      attack: "high",
      decay: "high",
      sustain: "high",
      release: "high",
    },
    ampEnv: { attack: "high", decay: "mid", sustain: "high", release: "high" },
  },
  {
    name: "Pluck / Synth Harp",
    category: "Bread-and-Butter Analog",
    blurb:
      'A bright, percussive pluck: saw or square gives harmonic content for the resonance to grab onto, and a fast decay on both envelopes gives that classic "harp string" snap.',
    osc: "Osc 1 shape: saw or square",
    mixer: "Osc 1 up front, Osc 2 low or an octave up for extra sparkle",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "high", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "low", noise: "min" },
    filterText: 'Cutoff mid, high resonance for the "ping", Env Amount high',
    filterEnvText: "Fast Attack, fast Decay, low Sustain, short Release",
    ampEnvText: "Fast Attack, fast Decay, low Sustain, short Release",
    filter: { cutoff: "mid", resonance: "high", drive: "low" },
    filterEnv: { attack: "min", decay: "min", sustain: "min", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "min", release: "low" },
  },
  {
    name: "Analog Brass",
    category: "Bread-and-Butter Analog",
    blurb:
      'A punchy synth-brass stab: saw waves for edge, medium resonance to give the filter sweep some bite, and a fast attack so the "blat" of a real brass hit comes through.',
    osc: "Osc 1 + Osc 2 both saw, Osc 2 detuned slightly for thickness",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "mid", pitch: "low", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText:
      "Cutoff mid, medium resonance, Env Amount high for the classic brass sweep",
    filterEnvText:
      "Fast Attack, medium Decay, mid Sustain, short-medium Release",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "mid" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Analog Strings",
    category: "Bread-and-Butter Analog",
    blurb:
      "A classic string-machine wash: detuned saws for that unmistakable ensemble shimmer, filter left half-open for a mellow top end, and a slow attack so notes bow in rather than snap.",
    osc: "Osc 1 + Osc 2 both saw, Osc 2 detuned",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "mid", pitch: "low", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText: "Cutoff half-open (mid), low-to-moderate resonance",
    filterEnvText: "Slow Attack, long Decay, high Sustain, long Release",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "mid", resonance: "low", drive: "min" },
    filterEnv: {
      attack: "high",
      decay: "high",
      sustain: "high",
      release: "high",
    },
    ampEnv: { attack: "high", decay: "low", sustain: "high", release: "high" },
  },
  {
    name: "Classic Analog Lead",
    category: "Leads & Solo Instruments",
    blurb:
      "A confident, singable lead: saw or PWM for a rich harmonic base, filter left half-open so it cuts through a mix, with glide and vibrato for expressive phrasing.",
    osc: "Osc 1 shape: saw or PWM; Glide on for note-to-note slides",
    mixer: "Osc 1 up front, Osc 2 an octave up or unison for thickness",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "high", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "mid", noise: "min" },
    filterText: "Cutoff half-open, moderate resonance",
    filterEnvText: "Fast Attack, short Decay, high Sustain, short Release",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "min" },
    filterEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "PWM Lead",
    category: "Leads & Solo Instruments",
    blurb:
      "A wide, chorus-like lead built entirely from pulse-width modulation - the square wave shape is constantly swept by an LFO, creating movement without needing a second detuned oscillator.",
    osc: "Osc 1 shape: square, Shape knob modulated by LFO for PWM",
    mixer: "Osc 1 up front",
    osc1: { shape: "low", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText:
      "Cutoff mid-high, low resonance (letting the PWM motion do the work)",
    filterEnvText: "Fast Attack, high Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "high", resonance: "low", drive: "min" },
    filterEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Sync Lead",
    category: "Leads & Solo Instruments",
    blurb:
      "An aggressive, ripping lead using hard sync - Osc 2 is forcibly reset by Osc 1, and sweeping Osc 2 with a pitch envelope produces that classic tearing sync sweep.",
    osc: "Sync 2→1 engaged; Osc 2 Pitch swept by a pitch envelope",
    mixer: "Osc 1 and Osc 2 balanced (sync needs both audible)",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: true },
    osc2: { shape: "high", octave: "mid", pitch: "high", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText:
      "Cutoff mid-high, moderate resonance to emphasize the sync harmonics",
    filterEnvText: "Fast Attack, medium Decay, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "high", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "FM Lead (Take 5 linear FM)",
    category: "Leads & Solo Instruments",
    blurb:
      "Using the Take 5's linear FM, Osc 2 lightly modulates Osc 1's pitch at audio rate - enough to add a metallic edge to the tone without turning it into a full bell/clang.",
    osc: "Osc 2 lightly FM-modulating Osc 1; keep FM amount subtle",
    mixer: "Osc 1 up front (it’s the carrier)",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: true, osc2: "low", noise: "min" },
    filterText: "Cutoff mid-high, moderate resonance",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "high", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Triangle/Resonant Lead",
    category: "Leads & Solo Instruments",
    blurb:
      "A smoother, rounder lead than the saw-based ones - the triangle wave is already gentle, so high resonance can be pushed hard for character without turning harsh.",
    osc: "Osc 1 shape: triangle",
    mixer: "Osc 1 up front",
    osc1: { shape: "min", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Cutoff mid, high resonance for a vocal-ish emphasis",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "high", drive: "min" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "LFO Filter Sweeps",
    category: "Motion & Modulated",
    blurb:
      "A slowly evolving pad or drone where the filter itself is the instrument - a slow LFO continuously sweeps the cutoff, so the tone breathes in and out on its own.",
    osc: "Osc 1 + Osc 2 both saw or triangle, detuned slightly",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "mid", pitch: "low", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText:
      "Cutoff mid (LFO-modulated), moderate resonance to make the sweep audible",
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "min" },
    filterEnv: {
      attack: "high",
      decay: "mid",
      sustain: "high",
      release: "high",
    },
    ampEnv: { attack: "high", decay: "mid", sustain: "high", release: "high" },
  },
  {
    name: "PWM Motion",
    category: "Motion & Modulated",
    blurb:
      "An animated, breathing square-wave timbre - Shape (pulse width) is continuously modulated so the harmonic content itself shifts over time rather than the filter.",
    osc: "Osc 1 shape: square, Shape knob under LFO modulation",
    mixer: "Osc 1 up front",
    osc1: { shape: "low", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Cutoff mid, low resonance (let PWM carry the motion)",
    filterEnvText: "Mid Attack, high Sustain",
    ampEnvText: "Mid Attack, high Sustain, medium Release",
    filter: { cutoff: "mid", resonance: "low", drive: "min" },
    filterEnv: { attack: "mid", decay: "mid", sustain: "high", release: "mid" },
    ampEnv: { attack: "mid", decay: "mid", sustain: "high", release: "mid" },
  },
  {
    name: "Filter FM",
    category: "Motion & Modulated",
    blurb:
      "A gritty, metallic texture made by having an oscillator modulate the filter cutoff at audio rate - the harmonic content smears in a way a slow LFO sweep never could.",
    osc: "Osc 2 (or a fast LFO) routed to modulate Filter Cutoff at audio rate",
    mixer:
      "Osc 1 up front, Osc 2 low in the mix (it’s mostly a modulator here)",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "low", noise: "min" },
    filterText:
      "Cutoff mid, high resonance to emphasize the metallic harmonics",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "high", drive: "mid" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Cross-Modulation",
    category: "Motion & Modulated",
    blurb:
      "Osc 2 modulates Osc 1's pitch - subtle amounts give a gentle shimmer, pushed further it turns harsh and metallic. A great one to ride live with the FM/mod amount knob.",
    osc: "Osc 2 modulating Osc 1 pitch; start subtle, push for harsher results",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: true, osc2: "low", noise: "min" },
    filterText: "Cutoff mid-high, moderate resonance",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "high", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Random/S&H Modulation",
    category: "Motion & Modulated",
    blurb:
      "Chaotic, unpredictable drift - modulation from a sample-and-hold or random source into pitch/filter gives a vintage, slightly-out-of-control character.",
    osc: "Osc 1 + Osc 2, pitch or shape under random/S&H modulation",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "mid", pitch: "mid", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText:
      "Cutoff mid, moderate resonance, optionally under random modulation too",
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "low" },
    filterEnv: {
      attack: "high",
      decay: "mid",
      sustain: "high",
      release: "high",
    },
    ampEnv: { attack: "high", decay: "mid", sustain: "high", release: "high" },
  },
  {
    name: "Analog Kick",
    category: "Percussive & Plucked",
    blurb:
      "A punchy synth kick built from the filter itself: push resonance high enough that the filter self-oscillates into a sine-like tone, then sweep it down fast with a pitch envelope.",
    osc: "Osc 1 shape: triangle/sine-like (or rely on filter self-oscillation)",
    mixer: "Osc 1 up front, others off",
    osc1: { shape: "min", octave: "low", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText:
      "High resonance (near self-oscillation), Cutoff swept down fast by envelope",
    filterEnvText: "Fast Attack, fast Decay, min Sustain, short Release",
    ampEnvText: "Fast Attack, fast Decay, min Sustain, short Release",
    filter: { cutoff: "low", resonance: "max", drive: "low" },
    filterEnv: { attack: "min", decay: "min", sustain: "min", release: "min" },
    ampEnv: { attack: "min", decay: "min", sustain: "min", release: "min" },
  },
  {
    name: "Analog Snare (core tone only)",
    category: "Percussive & Plucked",
    blurb:
      'Just the tonal core of a snare - noise for the "crack" and triangle for the body, both gated by a fast filtered envelope. No effects/layering, so this is a starting point, not a full snare.',
    osc: "Osc 1 triangle for body; Noise source for the crack",
    mixer: "Osc 1 and Noise both present, Noise slightly forward",
    osc1: { shape: "min", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "mid", osc1Sub: "min", fm: false, osc2: "min", noise: "high" },
    filterText:
      "Cutoff mid-high, moderate resonance for a filtered noise burst",
    filterEnvText: "Fast Attack, fast Decay, min Sustain, short Release",
    ampEnvText: "Fast Attack, fast Decay, min Sustain, short Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "min", sustain: "min", release: "min" },
    ampEnv: { attack: "min", decay: "min", sustain: "min", release: "min" },
  },
  {
    name: "Toms",
    category: "Percussive & Plucked",
    blurb:
      'A tuned tom hit - triangle wave for a clean fundamental, a medium (not ultra-fast) decay so there’s some body, and a pitch envelope for the characteristic downward "thump".',
    osc: "Osc 1 shape: triangle, Pitch swept down by envelope",
    mixer: "Osc 1 up front",
    osc1: { shape: "min", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Cutoff low-mid, low resonance",
    filterEnvText: "Fast Attack, medium Decay, low Sustain, short Release",
    ampEnvText: "Fast Attack, medium Decay, low Sustain, short Release",
    filter: { cutoff: "low", resonance: "low", drive: "min" },
    filterEnv: { attack: "min", decay: "mid", sustain: "low", release: "low" },
    ampEnv: { attack: "min", decay: "mid", sustain: "low", release: "low" },
  },
  {
    name: "Claves / Clicks",
    category: "Percussive & Plucked",
    blurb:
      'A tiny, pitched click - high filter resonance "pinged" by a very fast envelope produces a short tuned tone with almost no sustain, like a woodblock or clave hit.',
    osc: "Osc 1 any shape (the filter ping dominates the timbre)",
    mixer: "Osc 1 low, mostly there to excite the filter",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "low", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: 'High resonance, Cutoff mid, Env Amount high for the "ping"',
    filterEnvText: "Instant Attack, instant Decay, min Sustain, min Release",
    ampEnvText: "Instant Attack, instant Decay, min Sustain, min Release",
    filter: { cutoff: "mid", resonance: "max", drive: "low" },
    filterEnv: { attack: "min", decay: "min", sustain: "min", release: "min" },
    ampEnv: { attack: "min", decay: "min", sustain: "min", release: "min" },
  },
  {
    name: "Resonant Plucks",
    category: "Percussive & Plucked",
    blurb:
      'A springy, resonant pluck - high resonance plus a fast filter envelope gives that "boing" character heard on a lot of classic sequenced synth-pop basslines and plucks.',
    osc: "Osc 1 shape: saw or square",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "High resonance, Cutoff mid, Env Amount high",
    filterEnvText: "Fast Attack, fast Decay, min Sustain, short Release",
    ampEnvText: "Fast Attack, fast Decay, min Sustain, short Release",
    filter: { cutoff: "mid", resonance: "high", drive: "low" },
    filterEnv: { attack: "min", decay: "min", sustain: "min", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "min", release: "low" },
  },
  {
    name: "Dark Drone",
    category: "Drones & Atmospheric",
    blurb:
      "A brooding, low-lit drone - detuned saws for mass, cutoff kept low so it stays dark, and a slow LFO keeps it slowly shifting rather than static.",
    osc: "Osc 1 + Osc 2 both saw, detuned",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "low", pitch: "mid", sync: false },
    osc2: { shape: "high", octave: "low", pitch: "low", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText: "Cutoff low, low-moderate resonance, slow LFO on cutoff",
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "min", resonance: "low", drive: "min" },
    filterEnv: {
      attack: "max",
      decay: "high",
      sustain: "high",
      release: "max",
    },
    ampEnv: { attack: "max", decay: "high", sustain: "high", release: "max" },
  },
  {
    name: "Hollow Drone",
    category: "Drones & Atmospheric",
    blurb:
      "A more open, airy drone than the dark version - triangle plus PWM gives a hollow, woody character, with the filter left half-open rather than closed down.",
    osc: "Osc 1 triangle, Osc 2 square under PWM",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "min", octave: "low", pitch: "mid", sync: false },
    osc2: { shape: "low", octave: "low", pitch: "mid", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText: "Cutoff half-open (mid), low resonance",
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "mid", resonance: "low", drive: "min" },
    filterEnv: {
      attack: "max",
      decay: "high",
      sustain: "high",
      release: "max",
    },
    ampEnv: { attack: "max", decay: "high", sustain: "high", release: "max" },
  },
  {
    name: "Noise-Based Wind/Air",
    category: "Drones & Atmospheric",
    blurb:
      "Filtered noise slowly modulated in cutoff makes a convincing wind or air texture - no oscillators needed, just the noise source shaped over time.",
    osc: "Oscillators off/very low; Noise source is the sound",
    mixer: "Noise up front, everything else off",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "min", osc1Sub: "min", fm: false, osc2: "min", noise: "high" },
    filterText:
      'Cutoff slowly modulated, moderate resonance for a "whooshing" character',
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "min" },
    filterEnv: {
      attack: "max",
      decay: "high",
      sustain: "high",
      release: "max",
    },
    ampEnv: { attack: "max", decay: "high", sustain: "high", release: "max" },
  },
  {
    name: "Sub Drone",
    category: "Drones & Atmospheric",
    blurb:
      "A pure, weighty low-end drone - push resonance so the filter self-oscillates into a clean sine, or use triangle, and keep cutoff low so it stays felt more than heard.",
    osc: "Osc 1 triangle/sine-like (or rely on filter self-oscillation)",
    mixer: "Osc 1 up front, others off",
    osc1: { shape: "min", octave: "low", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText:
      "Cutoff low, high resonance (near self-oscillation for a pure sub tone)",
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "min", resonance: "high", drive: "min" },
    filterEnv: {
      attack: "max",
      decay: "high",
      sustain: "high",
      release: "max",
    },
    ampEnv: { attack: "max", decay: "high", sustain: "high", release: "max" },
  },
  {
    name: "Hard Sync",
    category: "Aggressive / Experimental",
    blurb:
      "The most aggressive sync sound - Osc 2 hard-synced to Osc 1 with a pitch envelope sweeping it produces that unmistakable ripping, tearing sound.",
    osc: "Sync 2→1 engaged; Osc 2 Pitch swept hard by envelope",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: true },
    osc2: { shape: "high", octave: "mid", pitch: "max", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText: "Cutoff high, moderate-high resonance",
    filterEnvText: "Fast Attack, medium Decay, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "high", resonance: "high", drive: "mid" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Pseudo Ring-Mod",
    category: "Aggressive / Experimental",
    blurb:
      "High-rate FM stands in for true ring modulation, producing metallic, bell-like inharmonic tones - the Take 5’s linear FM pushed further than the FM Lead patch.",
    osc: "Osc 2 FM-modulating Osc 1 at a high amount",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: true, osc2: "low", noise: "min" },
    filterText: "Cutoff high, moderate resonance",
    filterEnvText: "Fast Attack, short Decay",
    ampEnvText: "Fast Attack, short-medium Decay, low Sustain",
    filter: { cutoff: "high", resonance: "mid", drive: "mid" },
    filterEnv: { attack: "min", decay: "low", sustain: "low", release: "low" },
    ampEnv: { attack: "min", decay: "mid", sustain: "low", release: "low" },
  },
  {
    name: "Filter Drive",
    category: "Aggressive / Experimental",
    blurb:
      "Push the ladder filter's Drive knob hard for growling, saturated basses and aggressive leads - the filter itself becomes a distortion stage.",
    osc: "Osc 1 shape: saw or square",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Drive high, Cutoff low-mid, moderate resonance",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "low", resonance: "mid", drive: "max" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Audio-Rate Modulation",
    category: "Aggressive / Experimental",
    blurb:
      "Osc 2 modulating the filter cutoff at audio rate produces harsh, digital-sounding textures - a more extreme version of the Filter FM patch, pushed into noisier territory.",
    osc: "Osc 2 modulating Filter Cutoff at audio rate, high amount",
    mixer: "Osc 1 up front, Osc 2 mostly acting as modulator",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "low", noise: "min" },
    filterText: "Cutoff mid, high resonance and Drive for extra harshness",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "high", drive: "high" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Self-Oscillating Filter Tone",
    category: "Aggressive / Experimental",
    blurb:
      "Push resonance all the way and the filter generates its own sine tone with no oscillator input at all - the filter itself becomes the sound source.",
    osc: "Oscillators off or very low - the filter is the sound source",
    mixer: "Everything off except what’s needed to excite the filter",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "min", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText:
      "Resonance at maximum (self-oscillation), Cutoff sets the pitch",
    filterEnvText: "Slow Attack, high Sustain",
    ampEnvText: "Slow Attack, high Sustain, long Release",
    filter: { cutoff: "mid", resonance: "max", drive: "min" },
    filterEnv: {
      attack: "high",
      decay: "mid",
      sustain: "high",
      release: "high",
    },
    ampEnv: { attack: "high", decay: "mid", sustain: "high", release: "high" },
  },
  {
    name: "FM Bell",
    category: "Bell-Like / Metallic",
    blurb:
      'Light FM plus high resonance and a short decay gives a clean bell strike - the inharmonic edge from FM is what separates "bell" from "pluck".',
    osc: "Osc 2 lightly FM-modulating Osc 1",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: true, osc2: "low", noise: "min" },
    filterText: "High resonance, Cutoff mid-high",
    filterEnvText: "Instant Attack, short Decay, min Sustain, short Release",
    ampEnvText: "Instant Attack, short Decay, min Sustain, short Release",
    filter: { cutoff: "high", resonance: "high", drive: "low" },
    filterEnv: { attack: "min", decay: "low", sustain: "min", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "min", release: "low" },
  },
  {
    name: "Sync Bell",
    category: "Bell-Like / Metallic",
    blurb:
      "Hard sync frozen at a bright, harmonically-rich setting, paired with a short envelope, gives a bright chiming tone rather than the ripping sweep of the Sync Lead.",
    osc: "Sync 2→1 engaged, Osc 2 Pitch held (not swept)",
    mixer: "Osc 1 and Osc 2 balanced",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: true },
    osc2: { shape: "high", octave: "mid", pitch: "high", low: false },
    mix: {
      osc1: "high",
      osc1Sub: "min",
      fm: false,
      osc2: "high",
      noise: "min",
    },
    filterText: "Cutoff high, moderate resonance",
    filterEnvText: "Instant Attack, short Decay, min Sustain, short Release",
    ampEnvText: "Instant Attack, short Decay, min Sustain, short Release",
    filter: { cutoff: "high", resonance: "mid", drive: "low" },
    filterEnv: { attack: "min", decay: "low", sustain: "min", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "min", release: "low" },
  },
  {
    name: "Filter-Ping Bell",
    category: "Bell-Like / Metallic",
    blurb:
      'High resonance "pinged" by an envelope on cutoff gives a bell-like tone from the filter itself - related to Claves/Clicks but tuned lower and left to ring slightly longer.',
    osc: "Osc 1 low or off - filter ping carries the tone",
    mixer: "Osc 1 low, mostly there to excite the filter",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "low", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "High resonance, Cutoff mid, Env Amount high",
    filterEnvText: "Instant Attack, short Decay, min Sustain, medium Release",
    ampEnvText: "Instant Attack, short Decay, min Sustain, medium Release",
    filter: { cutoff: "mid", resonance: "max", drive: "low" },
    filterEnv: { attack: "min", decay: "low", sustain: "min", release: "mid" },
    ampEnv: { attack: "min", decay: "low", sustain: "min", release: "mid" },
  },
  {
    name: "Bright at Top, Dark at Bottom",
    category: "Keyboard-Tracking Variants",
    blurb:
      "Filter keyboard tracking at roughly 50% means higher notes open the filter more than lower notes - a natural brightness curve that mimics how many acoustic instruments behave.",
    osc: "Osc 1 shape: saw or square",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Key Amount ~50%, Cutoff mid, moderate resonance",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "min" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Constant Brightness",
    category: "Keyboard-Tracking Variants",
    blurb:
      "Filter keyboard tracking at 100% keeps the same relative brightness across the whole keyboard - cutoff scales exactly with pitch, so a high note isn’t any duller-sounding than a low one.",
    osc: "Osc 1 shape: saw or square",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Key Amount 100%, Cutoff mid, moderate resonance",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "mid", drive: "min" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Dark Everywhere",
    category: "Keyboard-Tracking Variants",
    blurb:
      "With Key Amount at 0%, the filter cutoff is fixed regardless of what note is played - useful when you want a consistently dark or muted character across the whole range.",
    osc: "Osc 1 shape: saw or square",
    mixer: "Osc 1 up front",
    osc1: { shape: "high", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "high", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText: "Key Amount 0%, Cutoff fixed low",
    filterEnvText: "Fast Attack, mid Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "low", resonance: "mid", drive: "min" },
    filterEnv: { attack: "min", decay: "mid", sustain: "mid", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Sub Oscillator Tone",
    category: "Utility / Foundational",
    blurb:
      "Just the sub on its own - triangle or square an octave (or two) down, filtered low, as a building block to layer under other patches rather than a finished sound.",
    osc: "Osc 2 as sub: triangle or square, an octave or two below Osc 1",
    mixer: "Sub up front, everything else off",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "min", octave: "low", pitch: "mid", low: true },
    mix: { osc1: "min", osc1Sub: "high", fm: false, osc2: "min", noise: "min" },
    filterText: "Cutoff low, low resonance",
    filterEnvText: "Fast Attack, high Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "min", resonance: "min", drive: "min" },
    filterEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Pure Sine (via filter self-oscillation)",
    category: "Utility / Foundational",
    blurb:
      "The Take 5’s filter can self-oscillate into a clean sine tone with resonance maxed and no oscillator input - a genuinely pure fundamental with zero harmonics.",
    osc: "Oscillators off - filter self-oscillation is the sound source",
    mixer: "Everything off",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "min", osc1Sub: "min", fm: false, osc2: "min", noise: "min" },
    filterText:
      "Resonance at maximum (self-oscillation), Cutoff sets the pitch",
    filterEnvText: "Fast Attack, high Sustain",
    ampEnvText: "Fast Attack, high Sustain, short Release",
    filter: { cutoff: "mid", resonance: "max", drive: "min" },
    filterEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "high", release: "low" },
  },
  {
    name: "Noise Source",
    category: "Utility / Foundational",
    blurb:
      "The raw noise generator on its own - a building block for percussive transients (short, filtered bursts) or wind/breath textures (long, slowly filtered), depending on the envelope.",
    osc: "Oscillators off; Noise is the sound",
    mixer: "Noise up front, everything else off",
    osc1: { shape: "mid", octave: "mid", pitch: "mid", sync: false },
    osc2: { shape: "mid", octave: "mid", pitch: "mid", low: false },
    mix: { osc1: "min", osc1Sub: "min", fm: false, osc2: "min", noise: "high" },
    filterText:
      "Cutoff varies by use (high for transients, sweeping for air), moderate resonance",
    filterEnvText: "Depends on use: fast for transients, slow for air/wind",
    ampEnvText: "Depends on use: fast for transients, slow for air/wind",
    filter: { cutoff: "mid", resonance: "mid", drive: "min" },
    filterEnv: { attack: "min", decay: "low", sustain: "low", release: "low" },
    ampEnv: { attack: "min", decay: "low", sustain: "low", release: "low" },
  },
];
